# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
# reports:
#   exclude_contracts:
#     - SafeMath

compiler:
  solc:
    version: 0.8.2
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0" 
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0